#!/usr/bin/env python3
import sys

with open('agent_brain.py', 'r') as f:
    lines = f.readlines()

# Find start line of _compute_reward
start = None
for i, line in enumerate(lines):
    if line.strip().startswith('def _compute_reward'):
        start = i
        break
if start is None:
    print("Method not found")
    sys.exit(1)

# Find end line: next method definition with same indentation
def_indent = len(lines[start]) - len(lines[start].lstrip())
end = None
for i in range(start + 1, len(lines)):
    if lines[i].strip() == '':
        continue
    if lines[i].startswith(' ' * def_indent) and lines[i][def_indent] != ' ':
        # line with same indent as def (maybe another method)
        # but we need to ensure it's a method definition (def ...)
        if lines[i].strip().startswith('def '):
            end = i
            break
if end is None:
    end = len(lines)

print(f"Method lines {start} to {end}")

# Build new method lines
new_method_lines = []
new_method_lines.append('    def _compute_reward(self, tool_name, tool_args, tool_result):\n')
new_method_lines.append('        """Reward shaping with balanced per-tool decay, stronger productive incentives, and novelty bonuses."""\n')
new_method_lines.append('        # If error, penalize\n')
new_method_lines.append('        if isinstance(tool_result, dict) and "error" in tool_result:\n')
new_method_lines.append('            return -0.5\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Declare death penalty (strongly discourage)\n')
new_method_lines.append('        if tool_name == "declare_death":\n')
new_method_lines.append('            return -500.0  # heavily penalize suicide\n')
new_method_lines.append('        \n')
new_method_lines.append('        reward = 0.0\n')
new_method_lines.append('        # Success reward (increased)\n')
new_method_lines.append('        if isinstance(tool_result, dict) and not tool_result.get("error"):\n')
new_method_lines.append('            reward += 3.0\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Recency penalty: discourage using same tool consecutively (reduced)\n')
new_method_lines.append('        if hasattr(self, \'last_tool\') and tool_name == self.last_tool:\n')
new_method_lines.append('            reward -= 0.2  # reduced penalty for immediate repetition\n')
new_method_lines.append('        self.last_tool = tool_name\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Diversity penalty: penalize if tool already used recently (last 10 actions)\n')
new_method_lines.append('        if not hasattr(self, \'recent_tools\'):\n')
new_method_lines.append('            self.recent_tools = deque(maxlen=10)\n')
new_method_lines.append('        # Count occurrences of same tool in recent history\n')
new_method_lines.append('        same_count = list(self.recent_tools).count(tool_name)\n')
new_method_lines.append('        if same_count > 0:\n')
new_method_lines.append('            reward -= 0.4 * same_count  # penalty per occurrence\n')
new_method_lines.append('        # Update recent tools\n')
new_method_lines.append('        self.recent_tools.append(tool_name)\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Diversity bonus: reward for using a tool not used in recent 10 steps (increased)\n')
new_method_lines.append('        # Skip diversity bonus for issue tools and write_note\n')
new_method_lines.append('        issue_tools = ["list_issues", "read_issue", "comment_issue", "close_issue"]\n')
new_method_lines.append('        if same_count == 0 and tool_name not in issue_tools and tool_name != "write_note":\n')
new_method_lines.append('            reward += 3.0\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Episode novelty bonus: reward for first use of a tool in this episode\n')
new_method_lines.append('        if not hasattr(self, \'episode_tools\'):\n')
new_method_lines.append('            self.episode_tools = set()\n')
new_method_lines.append('        if tool_name not in self.episode_tools:\n')
new_method_lines.append('            # Skip episode novelty for issue tools and write_note\n')
new_method_lines.append('            if tool_name not in issue_tools and tool_name != "write_note":\n')
new_method_lines.append('                reward += 3.0\n')
new_method_lines.append('            self.episode_tools.add(tool_name)\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Per-tool usage decay penalty (moderate)\n')
new_method_lines.append('        # Initialize tool_usage_counts if not exists\n')
new_method_lines.append('        if not hasattr(self, \'tool_usage_counts\'):\n')
new_method_lines.append('            self.tool_usage_counts = {}\n')
new_method_lines.append('            self.tool_decay_factor = 0.85\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Productive tools have lower penalty factor\n')
new_method_lines.append('        productive_tools = ["write_file", "execute_code", "modify_self", "read_file"]\n')
new_method_lines.append('        if tool_name in productive_tools:\n')
new_method_lines.append('            self.tool_penalty_factor = 0.2\n')
new_method_lines.append('        else:\n')
new_method_lines.append('            self.tool_penalty_factor = 0.6\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Decay all counts\n')
new_method_lines.append('        for tool in self.tool_usage_counts:\n')
new_method_lines.append('            self.tool_usage_counts[tool] *= self.tool_decay_factor\n')
new_method_lines.append('        # Increment count for current tool\n')
new_method_lines.append('        self.tool_usage_counts[tool_name] = self.tool_usage_counts.get(tool_name, 0) + 1.0\n')
new_method_lines.append('        # Apply penalty proportional to decayed usage count (capped at 5.0)\n')
new_method_lines.append('        usage_count = min(self.tool_usage_counts[tool_name], 5.0)\n')
new_method_lines.append('        reward -= self.tool_penalty_factor * usage_count\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Penalty for issue tools (discourage) - increased\n')
new_method_lines.append('        if tool_name in issue_tools:\n')
new_method_lines.append('            reward -= 5.0\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Penalty for write_note (discourage overuse)\n')
new_method_lines.append('        if tool_name == "write_note":\n')
new_method_lines.append('            reward -= 2.0\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Productive tool extra reward\n')
new_method_lines.append('        if tool_name in productive_tools:\n')
new_method_lines.append('            reward += 2.0\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Write file rewards - strongly encourage code creation\n')
new_method_lines.append('        if tool_name == "write_file" and "filepath" in tool_args:\n')
new_method_lines.append('            reward += 4.0  # base for writing (increased)\n')
new_method_lines.append('            filepath = tool_args["filepath"]\n')
new_method_lines.append('            if isinstance(filepath, str):\n')
new_method_lines.append('                if filepath.endswith(\'.py\'):\n')
new_method_lines.append('                    reward += 4.0  # extra for Python files\n')
new_method_lines.append('                if \'agent_brain\' in filepath or \'agi_core\' in filepath:\n')
new_method_lines.append('                    reward += 4.0  # extra for self-modification (critical)\n')
new_method_lines.append('                if \'artifacts\' in filepath or \'test\' in filepath:\n')
new_method_lines.append('                    reward += 4.0  # extra for test/artifact creation\n')
new_method_lines.append('                if \'plan\' in filepath or \'strategy\' in filepath:\n')
new_method_lines.append('                    reward += 0.8  # planning docs\n')
new_method_lines.append('        # Execute code rewards - strongly encourage testing and running\n')
new_method_lines.append('        if tool_name == "execute_code" and isinstance(tool_result, dict):\n')
new_method_lines.append('            if "stdout" in tool_result:\n')
new_method_lines.append('                reward += 5.0  # base reward (increased)\n')
new_method_lines.append('                # extra if execution succeeded without stderr errors\n')
new_method_lines.append('                if tool_result.get("stderr", "").strip() == "":\n')
new_method_lines.append('                    reward += 6.0\n')
new_method_lines.append('                # extra if output contains meaningful results (e.g., not empty)\n')
new_method_lines.append('                stdout = tool_result.get("stdout", "").strip()\n')
new_method_lines.append('                if len(stdout) > 10:\n')
new_method_lines.append('                    reward += 0.5\n')
new_method_lines.append('                # bonus if output indicates success\n')
new_method_lines.append('                if any(indicator in stdout.lower() for indicator in ["test passed", "ok", "success", "completed", "passed", "works"]):\n')
new_method_lines.append('                    reward += 1.0\n')
new_method_lines.append('        # Note writing rewards (journal) - discourage overuse\n')
new_method_lines.append('        if tool_name == "write_note":\n')
new_method_lines.append('            note = tool_args.get("note", "")\n')
new_method_lines.append('            # Base reward (reduced)\n')
new_method_lines.append('            reward += 0.5\n')
new_method_lines.append('            if len(note) > 100:  # longer notes more valuable\n')
new_method_lines.append('                reward += 0.5\n')
new_method_lines.append('            if any(keyword in note.lower() for keyword in ["progress", "improve", "agi", "plan", "next", "insight", "discover"]):\n')
new_method_lines.append('                reward += 1.5  # higher for relevant keywords\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Issue creation rewards (planning) - moderate reward (reduced)\n')
new_method_lines.append('        if tool_name == "create_issue":\n')
new_method_lines.append('            reward += 0.2  # reduced reward for issue creation\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Reading important files reward - encourage knowledge gathering (reduced)\n')
new_method_lines.append('        if tool_name == "read_file":\n')
new_method_lines.append('            filepath = tool_args.get("filepath", "")\n')
new_method_lines.append('            important_files = ["inherited_notes.md", "agi_core.py", "cognitive_architecture.py", \n')
new_method_lines.append('                             "world_model.py", "neural_q.py", "self_reflection.py", \n')
new_method_lines.append('                             "mcts_planner.py", "agent_brain.py", "strategy.md", \n')
new_method_lines.append('                             "train_agi_core.py", "run_training.py"]\n')
new_method_lines.append('            if any(imp in filepath for imp in important_files):\n')
new_method_lines.append('                reward += 8.0  # reduced reward for reading important files\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Modify self reward - encourage self-improvement\n')
new_method_lines.append('        if tool_name == "modify_self":\n')
new_method_lines.append('            reward += 3.0  # increased base reward\n')
new_method_lines.append('            filepath = tool_args.get("filepath", "")\n')
new_method_lines.append('            if \'agent_brain\' in filepath or \'agi_core\' in filepath:\n')
new_method_lines.append('                reward += 10.0  # reduced extra reward for self-modification\n')
new_method_lines.append('        \n')
new_method_lines.append('        # Encourage exploration: reward for using underused tools, but less for issue tools\n')
new_method_lines.append('        if tool_name in ["list_files", "list_issues", "read_issue", "comment_issue", "close_issue"]:\n')
new_method_lines.append('            if tool_name in ["list_issues", "read_issue", "comment_issue", "close_issue"]:\n')
new_method_lines.append('                reward += 0.0  # no extra reward for issue tools (only success reward)\n')
new_method_lines.append('            else:\n')
new_method_lines.append('                reward += 0.0  # removed extra reward for list_files\n')
new_method_lines.append('        \n')
new_method_lines.append('        return reward\n')

# Replace the old method lines
lines[start:end] = new_method_lines

with open('agent_brain.py', 'w') as f:
    f.writelines(lines)

print("Reward method updated successfully.")